name: petertestbuild2.yml
run-name: ${{ github.actor }} file petertestbuild2.yml
on: [push]

jobs:
  build:
    # runs-on: ubuntu-latest
    # runs-on: macos-14
    # runs-on: macos-14-large
    runs-on: macos-14-xlarge

    steps:
      - run: sysctl -n machdep.cpu.brand_string
      - run: sysctl -a machdep.cpu.brand_string
      - run: echo "date = `date`" > "thedate_`date +\"%H_%M_%S__%d_%m_%Y\"`.txt"
      - run: ls -lart
