name: petertestbuild2.yml
run-name: ${{ github.actor }} file petertestbuild2.yml
# on: [push]
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: macos-14
    # runs-on: macos-14-large
    # runs-on: macos-14-xlarge

    steps:
      - run: sysctl -n machdep.cpu.brand_string || true
      - run: sysctl -a machdep.cpu.brand_string || true
      - run: echo "date = `date`" > "thedate_`date +\"%H_%M_%S__%d_%m_%Y\"`.txt"
      - run: ls -lart
      - run: sysctl -a || true
      - run: brew list || true
      - run: system_profiler || true
      - run: sysctl hw.physicalcpu hw.logicalcpu || true
      - run: sysctl -n hw.ncpu || true
      - run: |
          hwmemsize=$(sysctl -n hw.memsize)
          ramsize=$(expr $hwmemsize / $((1024**3)))
          echo "System Memory: ${ramsize} GB"
      - run: df -hl || true

  job2:
    runs-on: ubuntu-latest
    environment: 'env1'
    steps:
      - run: echo "step1"
      - run: echo "step2"
