
name: petertestbuild4.yml
run-name: ${{ github.actor }} file petertestbuild4.yml

on: workflow_dispatch

jobs:
  terraform_init:
    runs-on: ubuntu-latest
    steps:



      - name: tfstep1
        run: ls -lart || true

      - name: tfstep2
        run: ls -lart || .terraform


      - name: Checkout code
        uses: actions/checkout@v4

      - name: tfstep3
        run: ls -lart || true

      - name: tfstep4
        run: ls -lart || .terraform


      - name: Initialize Terraform
        run: terraform init
#         working-directory: terraform/config

      - name: tfstep5
        run: ls -lart || true

      - name: tfstep6
        run: ls -lart || .terraform


  terraform_apply:
    runs-on: ubuntu-latest
    needs: terraform_init
    steps:

      - name: tfstep1
        run: ls -lart || true

      - name: tfstep2
        run: ls -lart || .terraform

      - name: Checkout code
        uses: actions/checkout@v4

      - name: tfstep3
        run: ls -lart || true

      - name: tfstep4
        run: ls -lart || .terraform


      - name: Apply Terraform 1
        run: terraform apply -auto-approve || true
#         working-directory: terraform/config

      - name: tfstep5
        run: ls -lart || true

      - name: tfstep6
        run: ls -lart || .terraform



      - name: Initialize Terraform
        run: terraform init
#         working-directory: terraform/config


      - name: tfstep7
        run: ls -lart || true

      - name: tfstep8
        run: ls -lart || .terraform


      - name: Apply Terraform 2
        run: terraform apply -auto-approve
#         working-directory: terraform/config


      - name: tfstep9
        run: ls -lart || true

      - name: tfstep10
        run: ls -lart || .terraform

